name: Build and Publish Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Build ParallaxGenMutagenWrapper
      run: |
        cd ParallaxGenMutagenWrapper
        dotnet restore
        msbuild /p:Configuration=RelWithDebInfo

    - name: Run VCPKG
      uses: lukka/run-vcpkg@v11

    - name: Configure CMake
      run: |
        New-Item -ItemType Directory -Path "build" -Force
        cd build
        cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DCMAKE_INSTALL_PREFIX="../install" -DCMAKE_BUILD_TYPE=RelWithDebInfo

    - name: Build and Install ParallaxGen
      run: |
        cd build
        cmake --build . --target install --config RelWithDebInfo

    - name: Copy ParallaxGenMutagenWrapper build
      run: |
        New-Item -ItemType Directory -Path "build\ParallaxGenMutagenWrapper" -Force
        Copy-Item -Path ParallaxGenMutagenWrapper\bin -Destination build\ParallaxGenMutagenWrapper\ -Recurse -Force
        Copy-Item -Path ParallaxGenMutagenWrapper\obj -Destination build\ParallaxGenMutagenWrapper\ -Recurse -Force

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: parallaxgen-release-artifacts-${{ github.sha }}
        path: install

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: parallaxgen-build-artifacts-${{ github.sha }}
        path: build
