name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Cache VCPKG
      uses: actions/cache@v3
      with:
        key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
        path: |
          build/vcpkg_installed

    - name: Cache Externals
      uses: actions/cache@v3
      with:
        key: externals-${{ runner.os }}-${{ hashFiles('.gitmodules') }}
        path: |
          build/external

    - name: Build ParallaxGenMutagenWrapper
      run: |
        cd ParallaxGenMutagenWrapper
        dotnet restore
        msbuild /p:Configuration=RelWithDebInfo

    - name: Configure CMake
      run: |
        New-Item -ItemType Directory -Path "build" -Force
        cd build
        cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DCMAKE_INSTALL_PREFIX="../install" -DCMAKE_BUILD_TYPE=RelWithDebInfo

    - name: Build and Install ParallaxGen
      run: |
        cd build
        cmake --build . --target install --config RelWithDebInfo

        - name: Download Clang
        uses: robinraju/release-downloader@v1
        with:
          repository: 'llvm/llvm-project'
          tag: 'llvmorg-19.1.7'
          fileName: 'clang+llvm-19.1.7-x86_64-pc-windows-msvc.tar.xz'
          out-file-path: 'clang'
          extract: false

    - name: Extract Clang
      uses: ihiroky/extract-action@v1
      with:
        file_path: 'clang\\clang+llvm-19.1.7-x86_64-pc-windows-msvc.tar.xz'
        extract_dir: 'clang'

    - name: Add Clang to PATH
      run: echo "clang\\clang+llvm-19.1.7-x86_64-pc-windows-msvc\\bin" >> $Env:GITHUB_PATH
      shell: pwsh

    - name: Verify Clang Installation version
      run: clangd --version

    - name: Set up python
      uses: actions/setup-python@v3
    - name: Linting checks
      uses: pre-commit/action@v3.0.1

    - name: Copy ParallaxGenMutagenWrapper build
      run: |
        New-Item -ItemType Directory -Path "build\ParallaxGenMutagenWrapper" -Force
        Copy-Item -Path ParallaxGenMutagenWrapper\bin -Destination build\ParallaxGenMutagenWrapper\ -Recurse -Force
        Copy-Item -Path ParallaxGenMutagenWrapper\obj -Destination build\ParallaxGenMutagenWrapper\ -Recurse -Force

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: parallaxgen-release-artifacts-${{ github.sha }}
        path: install

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: parallaxgen-build-artifacts-${{ github.sha }}
        path: build
