name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - uses: robinraju/release-downloader@v1
      with:
        repository: 'llvm/llvm-project'
        tag: 'llvmorg-19.1.7'
        fileName: 'clang+llvm-19.1.7-x86_64-pc-windows-msvc.tar.xz'
        out-file-path: 'clang'
        extract: true

    - name: Add LLVM Clang to PATH
      run: echo "clang\\clang+llvm-19.1.7-x86_64-pc-windows-msvc\\bin" >> $Env:GITHUB_PATH
      shell: pwsh

    - name: Verify LLVM Clang Installation
      run: clangd --version

    - name: Configure CMake
      run: |
        New-Item -ItemType Directory -Path "build" -Force
        cd build
        cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DCMAKE_INSTALL_PREFIX="../install" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Set up python
      uses: actions/setup-python@v3
    - name: Linting checks
      uses: pre-commit/action@v3.0.1
